services:
  icklist_database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ickListBackend
      MYSQL_DATABASE: ickList
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: secret
    restart: on-failure
  icklist_backend:
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: Backend
    ports:
      - 8080:8080
    depends_on:
      - icklist_database
  icklist_frontend:
    environment:
      API_URL: api.icklist.justusvonvoss.me
    build:
      dockerfile: Dockerfile
      context: Frontend
    ports:
      - 3000:3000
