services:
  icklist_database:
    container_name: icklist_database-local
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ickListBackend
      MYSQL_DATABASE: ickList
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: secret
    restart: on-failure
    volumes:
      - database:/var/lib/mysql
  icklist_backend:
    container_name: icklist_backend-local
    environment:
      DB_URL: jdbc:mysql://localhost:3306/ickList
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: ../Backend
    ports:
      - 8080:8080
    depends_on:
      - icklist_database
    volumes:
      - backend:/home/gradle/.gradle
volumes:
  database:
  backend: