services:
  icklist_database_int:
    image: mysql
    ports:
      - 20013:3306
    environment:
      MYSQL_USER: ickListBackend
      MYSQL_DATABASE: ickList
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: secret
    restart: on-failure
  icklist_backend_int:
    environment:
      DB_URL: jdbc:mysql://localhost:20013/ickList
    network_mode: host
    image: localhost:5000/icklist-backend-int:latest
    ports:
      - 20011:8080
    depends_on:
      - icklist_database_int
  icklist_frontend_int:
    environment:
      API_URL: api.icklist-int.justusvonvoss.me
    image: localhost:5000/icklist-frontend-int:latest
    ports:
      - 20012:3000
