services:
  icklist_database_prod:
    image: mysql
    ports:
      - 20003:3306
    environment:
      MYSQL_USER: ickListBackend
      MYSQL_DATABASE: ickList
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: secret
    restart: on-failure
  icklist_backend_prod:
    environment:
      DB_URL: jdbc:mysql://89.191.68.204:20003/ickList
    image: localhost:5000/icklist-backend:latest
    ports:
      - 20001:8080
    depends_on:
      - icklist_database_prod
  icklist_frontend_prod:
    environment:
      NEXT_PUBLIC_API_URL: api.icklist.justusvonvoss.me
    image: localhost:5000/icklist-frontend:latest
    ports:
      - 20002:3000
