apiVersion: apps/v1
kind: Deployment
metadata:
  name: icklist-backend
  labels:
    app: icklist-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icklist-backend
  template:
    metadata:
      labels:
        app: icklist-backend
    spec:
      containers:
        - name: icklist-backend
          image: docker.lab.qstetten.de/icklist-backend:4a0d3dfa369e9f4c296df8564dede141856364a2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-sto
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://sto-01:3306/icklist"
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: icklist-backend
spec:
  selector:
    app: icklist-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: icklist-backend
spec:
  tls:
    - hosts:
        - api.icklist.vonvoss.de
        - api.icklist.justusvonvoss.de
      secretName: icklist2-backend-cert
  rules:
    - host: "api.icklist.vonvoss.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: icklist-backend
                port:
                  number: 80
    - host: "api.icklist.justusvonvoss.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: icklist-backend
                port:
                  number: 80
