apiVersion: apps/v1
kind: Deployment
metadata:
  name: icklist-frontend
  labels:
    app: icklist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icklist-frontend
  template:
    metadata:
      labels:
        app: icklist-frontend
    spec:
      containers:
        - name: icklist-frontend
          image: docker.lab.qstetten.de/icklist-frontend:d634d23eb6669708b3eba5d02e6044aef2467220
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: icklist-frontend
spec:
  selector:
    app: icklist-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: icklist-frontend
spec:
  tls:
    - hosts:
        - icklist.vonvoss.de
      secretName: icklist-frontend-cert
  rules:
    - host: "icklist.vonvoss.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: icklist-frontend
                port:
                  number: 80
