apiVersion: apps/v1
kind: Deployment
metadata:
  name: icklist-backend
  labels:
    app: icklist-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icklist-backend
  template:
    metadata:
      labels:
        app: icklist-backend
    spec:
      containers:
        - name: icklist-backend
          image: registry.lab.lcarilla.de/icklist-backend:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-sto
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://sto-01:3306"
      imagePullSecrets:
        - name: lab-registry
---
kind: Service
apiVersion: v1
metadata:
  name: icklist-backend
spec:
  selector:
    app: icklist-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: icklist-backend
spec:
  tls:
    - hosts:
        - api.icklist.justusvonvoss.me
      secretName: icklist-backend-cert
  rules:
    - host: "api.icklist.justusvonvoss.me"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: icklist-backend
                port:
                  number: 80