name: Deploy Backend Prod
on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: docker.lab.qstetten.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "docker.lab.qstetten.de/icklist-backend:${{ github.sha }}"
      - name: Update Image Tag in k8s backend ressources
        run: |
         sed -i 's|docker\.lab\.qstetten\.de/icklist-backend:[^[:space:]]*|docker.lab.qstetten.de/icklist-backend:${{ github.sha }}|' Deployment/k8s-backend.yaml
         cat Deployment/k8s-backend.yaml
        shell: bash
      - name: Commit updated k8s ressource
        run: |
          git config --global user.name '${{ secrets.DEPLOYMENT_NAME }}'
          git config --global user.email '${{ secrets.DEPLOYMENT_EMAIL }}'
          git add Deployment/k8s-backend.yaml
          git commit -m 'Updatet backend image to ${{ github.sha }}'
          git push
        shell: bash
