name: Deploy Frontend Prod
on:
  push:
    branches:
      - counter
    paths:
      - 'Frontend/**'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: docker.lab.qstetten.de
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          file: Frontend/Docker/Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "docker.lab.qstetten.de/icklist-frontend:${{ github.sha }}"
      - name: Update Image Tag in k8s frontend ressources
        run: |
         sed -i 's|docker\.lab\.qstetten\.de/icklist-frontend:[^[:space:]]*|docker.lab.qstetten.de/icklist-frontend:${{ github.sha }}|' Deployment/k8s-frontend.yaml
         cat Deployment/k8s-frontend.yaml
        shell: bash
      - name: Commit updated k8s ressource
        run: |
          git config --global user.name 'IckListDeploymentManagement'
          git config --global user.email 'deployment@users.noreply.github.com'
          git add Deployment/k8s-frontend.yaml
          git commit -m 'Updatet frontend image to ${{ github.sha }}'
          git push
        shell: bash
