name: Deploy Frontend Prod

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Run script file
        run: |
         sed -i 's|docker\.lab\.qstetten\.de/icklist-backend:[^[:space:]]*|docker.lab.qstetten.de/icklist-backend:${{ github.sha }}|' Deployment/k8s-frontend.yaml
         cat Deployment/k8s-frontend.yaml
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v5
