name: Deploy Frontend Prod

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          file: Frontend/Docker/Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "${{ secrets.REGISTRY_URL }}/icklist-frontend:${{ github.sha }}"
      - name: Run script file
        run: |
         sed -i 's|docker\.lab\.qstetten\.de/icklist-backend:[^[:space:]]*|docker.lab.qstetten.de/icklist-backend:${{ github.sha }}|' k8s-frontend.yaml
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v5
